version: '2.3'
services:
  bot:
    image: ghcr.io/ashishdotme/ansu
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure
    volumes:
      - type: bind
        source: ./Lists/rudeWords.txt
        target: /app/Lists/rudeWords.txt
    environment:
      # Overrides your configs Redis options for use with Docker Compose
      #  I don't advise changing this unless you have a strange setup
      - REDIS_DOCKER_OVERRIDE=true
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: --appendonly yes
